name: Populate Database

on:
  workflow_dispatch:  # Triggered manually

jobs:
  import-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Import BACPAC file to Azure SQL Database
        run: |
          az sql db import \
            --admin-password ${{ secrets.AZURE_SQL_ADMIN_PASSWORD }} \
            --admin-user ${{ secrets.AZURE_SQL_ADMIN_USER }} \
            --name sqldb-calicot-dev-${{ secrets.CODE_ID }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --server sqlsrv-calicot-dev-${{ secrets.CODE_ID }} \
            --storage-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --storage-key-type StorageAccessKey \
            --storage-uri "https://your-storage-account-name.blob.core.windows.net/your-container/auctions_data.bacpac"
