name: Import Database via BACPAC

on:
  workflow_dispatch:  # Déclenchement manuel via GitHub UI

jobs:
  import-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure Credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Import BACPAC to Azure SQL
      run: |
        az sql db import \
          --resource-group ${RESOURCE_GROUP} \
          --server ${SQL_SERVER_NAME} \
          --name ${SQL_DATABASE_NAME} \
          --storage-key ${STORAGE_ACCOUNT_KEY} \
          --storage-uri ${STORAGE_URI}/Auctions_Data.bacpac
