name: Deploy Infrastructure via Terraform

on:
  workflow_dispatch:  # Déclenchement manuel via GitHub Actions UI

jobs:
  terraform:
    runs-on: ubuntu-latest  # Utilisation de l'image Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.0'  # Version de Terraform à utiliser

    - name: Set up Azure Credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Les secrets Azure pour l'authentification

    - name: Initialize Terraform
      run: terraform init  # Initialisation des fichiers Terraform

    - name: Validate Terraform Configuration
      run: terraform validate  # Validation des fichiers Terraform

    - name: Plan Terraform Changes
      run: terraform plan  # Génère le plan de déploiement

    - name: Apply Terraform Configuration
      run: terraform apply -auto-approve  # Applique les modifications sans demande de confirmation
